Azure_Snowflake_Dbt:
  outputs:
    dev:
      account: LEHJBER-HW50611
      database: AZURE_DBT_SNOWFLAKE
      password: Chintu@16051992
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: RAM
      warehouse: COMPUTE_WH
  target: dev
