SELECT
    TRIP_ID,
    CUSTOMER_ID,
    DRIVER_ID,
    VEHICLE_ID,
    LOCATION_ID,
    TRIP_START_TIME,
    TRIP_END_TIME,
    TRIP_DISTANCE,
    TRIP_DURATION_MINUTES,
    TRIP_AMOUNT,
    DRIVER_RATING,
    TRIP_STATUS,
    TRIP_PAYMENT_METHOD,
    TRIP_FARE_TIER,
    TRIP_DISTANCE_CATEGORY,
    TRIP_LAST_UPDATED

FROM {{ ref('obt') }}